apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference-app-agenda-service-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: agenda-service
  template:
    metadata:
      labels:
        app: agenda-service
        app.kubernetes.io/name: agenda-service
        app.kubernetes.io/part-of: agenda-service
        app.kubernetes.io/version: v1.0.0
        keptn.sh/post-deployment-tasks: stdout-notification
    spec:
      containers:
      - name: agenda-service
        image: "salaboy/agenda-service-0967b907d9920c99918e2b91b91937b3:v1.0.0"
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          value: conference-app-kafka.default.svc.cluster.local
        - name: REDIS_HOST
          value: conference-app-redis-master.default.svc.cluster.local
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: conference-app-redis
              key: redis-password
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        ports:
        - containerPort: 8080