apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service-deployment
spec:
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      annotations:  
        dapr.io/app-id: notifications-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: ko://github.com/salaboy/platforms-on-k8s/conference-application/notifications-service
        imagePullPolicy: Always
        env:          
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName      
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 80
    targetPort: 8080