apiVersion: v2
description: A Helm chart for the Conference App
name: conference-app
version: v1.0.0
type: application
icon: https://www.salaboy.com/content/images/2023/06/avatar-new.png
appVersion: v1.0.0
maintainers:
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/platforms-on-k8s
dependencies:
  - name: redis
    version: 17.11.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: install.infrastructure
  - name: postgresql
    version: 12.5.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: install.infrastructure
  - name: kafka
    version: 22.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: install.infrastructure
keywords:
  - cloudnative
  - platform-engineering
  - platforms
  - book
  - kubernetes
  - tutorial
  - example