services:
  registry: salaboy
  tag: v1.0.0
  frontend: 
    image: frontend-go-1739aa83b5e69d4ccb8a5615830ae66c
  agenda: 
    image: agenda-service-0967b907d9920c99918e2b91b91937b3 
  c4p: 
    image: c4p-service-a3dc0474cbfa348afcdf47a8eee70ba9
  notifications: 
    image: notifications-service-0e27884e01429ab7e350cb5dff61b525
install:
  infrastructure: true
  ingress: true
postgresql:
  image:
    debug: true
  primary: 
    persistence:
      size: "1Gi"
    initdb:
      user: postgres
      password: postgres
      scriptsConfigMap: c4p-init-sql
  global:
    postgresql:
      auth: 
        postgresPassword: postgres
redis: 
  architecture: standalone
  master:
    persistence:
      size: "1Gi"
kafka: 
  persistence:
    size: "1Gi"
  provisioning:
    topics:
    - name: events-topic
      partitions: 1