apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-c4p-service-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: c4p-service
  template:
    metadata:
      labels:
        app: c4p-service
        app.kubernetes.io/name: c4p-service
        app.kubernetes.io/part-of: c4p-service
        app.kubernetes.io/version: {{ .Values.services.tag  }}
        keptn.sh/post-deployment-tasks: stdout-notification
    spec:
      containers:
      - name: c4p-service
        image: "{{ .Values.services.registry }}/{{ .Values.services.c4p.image }}:{{ .Values.services.tag }}"
        imagePullPolicy: Always
        env:
        - name: AGENDA_SERVICE_URL
          value: http://agenda-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: NOTIFICATIONS_SERVICE_URL
          value: http://notifications-service.{{ .Release.Namespace }}.svc.cluster.local
{{- if .Values.install.infrastructure }} 
        - name: KAFKA_URL
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgres-password 
{{- else }}
        - name: KAFKA_URL
          value: {{ .Values.c4p.kafka.url}}
        - name: POSTGRES_HOST
          value: {{ .Values.c4p.postgresql.host}}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.c4p.postgresql.secretName}}
              key: postgres-password 
{{- end }}                
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName       
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c4p-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: c4p-service
  ports:
  - port: 80
    targetPort: 8080