apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference-app-c4p-service-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: c4p-service
  template:
    metadata:
      labels:
        app: c4p-service
        app.kubernetes.io/name: c4p-service
        app.kubernetes.io/part-of: c4p-service
        app.kubernetes.io/version: v1.0.0
        keptn.sh/post-deployment-tasks: stdout-notification
    spec:
      containers:
      - name: c4p-service
        image: "salaboy/c4p-service-a3dc0474cbfa348afcdf47a8eee70ba9:v1.0.0"
        imagePullPolicy: Always
        env:
        - name: AGENDA_SERVICE_URL
          value: http://agenda-service.default.svc.cluster.local
        - name: NOTIFICATIONS_SERVICE_URL
          value: http://notifications-service.default.svc.cluster.local
        - name: KAFKA_URL
          value: conference-app-kafka.default.svc.cluster.local
        - name: POSTGRES_HOST
          value: conference-app-postgresql.default.svc.cluster.local
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: conference-app-postgresql
              key: postgres-password
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        ports:
        - containerPort: 8080