apiVersion: eazytraining.io/v1alpha1
kind: Environment
metadata:
  name: team-a-dev-env
spec:
  writeConnectionSecretToRef:
    name: team-a-dev-env
  compositionSelector:
    matchLabels:
      type: development
  parameters: 
    installInfra: true
    frontend:
      debug: true
    