apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agenda-service-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: agenda-service
  template:
    metadata:
      labels:
        app: agenda-service
        app.kubernetes.io/name: agenda-service
        app.kubernetes.io/part-of: agenda-service
        app.kubernetes.io/version: {{ .Values.services.tag  }}
        keptn.sh/post-deployment-tasks: stdout-notification
    spec:
      containers:
      - name: agenda-service
        image: "{{ .Values.services.registry }}/{{ .Values.services.agenda.image }}:{{ .Values.services.tag  }}"
        imagePullPolicy: Always
        env:
 {{- if .Values.install.infrastructure }}       
        - name: KAFKA_URL
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-redis
              key: redis-password
{{- else }}
        - name: KAFKA_URL
          value: {{ .Values.agenda.kafka.url}}
        - name: REDIS_HOST
          value: {{ .Values.agenda.redis.host}}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.agenda.redis.secretName}}
              key: redis-password
{{- end }}              
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName      
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agenda-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: agenda-service
  ports:
  - port: 80
    targetPort: 8080
