apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: frontend
        app.kubernetes.io/version: {{ .Values.services.tag  }}
        keptn.sh/post-deployment-tasks: stdout-notification
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.services.registry }}/{{ .Values.services.frontend.image }}:{{ .Values.services.tag }}"
        imagePullPolicy: Always
        env: 
{{- if .Values.services.frontend.debug }}
        - name: FEATURE_DEBUG_ENABLED
          value: "true"
{{- end }}
        - name: AGENDA_SERVICE_URL
          value: http://agenda-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: C4P_SERVICE_URL
          value: http://c4p-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: NOTIFICATIONS_SERVICE_URL
          value: http://notifications-service.{{ .Release.Namespace }}.svc.cluster.local  
{{- if .Values.install.infrastructure }}         
        - name: KAFKA_URL
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local
{{- else }}
        - name: KAFKA_URL
          value: {{ .Values.frontend.kafka.url}}
{{- end }}                         
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName  
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080