apiVersion: v1
kind: Secret
metadata:
  name: conference-app-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.11.3
    app.kubernetes.io/instance: conference-app
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "bnJDblVaWGJDdQ=="