services:
  registry: salaboy
  tag: v2.0.0
  frontend: 
    image: frontend-go-1739aa83b5e69d4ccb8a5615830ae66c
  agenda: 
    image: agenda-service-0967b907d9920c99918e2b91b91937b3 
  c4p: 
    image: c4p-service-a3dc0474cbfa348afcdf47a8eee70ba9
  notifications: 
    image: notifications-service-0e27884e01429ab7e350cb5dff61b525
install:
  infrastructure: true
  ingress: true
postgresql: #helm install postgresql bitnami/postgresql --version 12.5.7 --set "image.debug=true" --set "primary.initdb.user=postgres" --set "primary.initdb.password=postgres" --set "primary.initdb.scriptsConfigMap=c4p-init-sql" --set "global.postgresql.auth.postgresPassword=postgres"
  image:
    debug: true
  primary: 
    persistence:
      size: "1Gi"
    initdb:
      user: postgres
      password: postgres
      scriptsConfigMap: c4p-init-sql
  global:
    postgresql:
      auth: 
        postgresPassword: postgres
redis: #helm install redis bitnami/redis --version 17.11.3 --set "architecture=standalone"
  architecture: standalone
  master:
    persistence:
      size: "1Gi"
kafka: 
  persistence:
    size: "1Gi"
kafka: # helm install kafka bitnami/kafka --version 22.1.5 --set "provisioning.topics[0].name=events-topic" --set "provisioning.topics[0].partitions=1" 
  provisioning:
    topics:
    - name: events-topic
      partitions: 1