apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: messagebrokers.eazytraining.io
spec:
  group: eazytraining.io
  names:
    kind: MessageBroker
    plural: messagebrokers
    shortNames:
      - "mb"
      - "mbs"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.parameters.size
      name: SIZE
      type: string
    - jsonPath: .spec.compositionSelector.matchLabels.kind
      name: KIND
      type: string
    name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              parameters: 
                type: object
                properties:
                  size:
                    type: string 
                required:   
                - size
            required: 
            - parameters     